version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # PGDATA: ./data/postgres
    # volumes:
      #  - ./postgres:/data/postgres
      #  - ./src_data.csv:/data/src_data/src_data.csv
      #  - ./create_seed_data.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
